packages:
  - packages/*
  - common/*

catalog:
  '@types/node': ^24.6.0
  '@types/three': 0.176.0
  '@vitejs/plugin-vue': ^6.0.1
  'three': 0.176.0
  'rollup-plugin-visualizer': ^6.0.1
  'vue': ^3.5.22
  "vite-plugin-static-copy": ^3.1.0
  'vite': ^6.2.5 #npm:rolldown-vite@7.1.14
  'typescript': ^5.4.5
  'naive-ui': ^2.43.1

autoInstallPeers: true
